#Varying the number of workers
seed: 1
nums_workers: [8,12,16,20]
alpha: 1
length_scale: 0.1
nu: 0.5
num_samples: 10000
min_dis: 0.02
coefficients: [-1, 2, 3, -2, 1]
noise_level: 2
num_knots: 100
step_size: 0.2
concurrencies_dict: 
  8: [2, 4, 6, 8]
  12: [2, 4, 6, 8, 10, 12]
  16: [4, 6, 8, 10, 12, 14, 16]
  20: [4, 6, 8, 10, 12, 14, 18, 20]

